### ISSUE TITLE
Methods are now deprecated

### ISSUE THREAD

**Issue by cdecinkoKnight** [ChristianHuff-DEV/secure-spring-rest-api-using-keycloak#1]
This solution is no longer valid for Spring Security 6.1+. Is there an updated version?

**Comment by ChristianHuff-DEV** [comment]
Thanks for letting me know.

I created a branch (https://github.com/ChristianHuff-DEV/secure-spring-rest-api-using-keycloak/tree/update-spring) that updates Spring Boot and replaces the deprecate methods. Feel free to give it a try and let me know if it works.

**Comment by cdecinkoKnight** [comment]
Sorry, forgot to let you know, this looks to be working. Thank you
